version : "3"

services:
  rest_training:
    build: .
    image: rest_training:development
    ports:
      - 5000:5000
    volumes:
      - ./app:/env_p36/app

networks: 
  default:
    external:
      name: my-shared-network